name: ReplenishPlugin
version: ${version}
api-version: "1.21"
main: cancelcloud.ReplenishPlugin
bootstrapper: cancelcloud.enchantment.replenish.ReplenishBootstrap
description: "Custom Replenish enchantment für automatisches Neupflanzen von Pflanzen"
